
binance:
    api-key: "redacted"
    ed25519-secret-path: "redacted"
    base-url: "https://testnet.binance.vision" # Prod would be https://api.binance.com
    base-websocket: "wss://testnet.binance.vision" # Prod would be wss://stream.binance.com:9443
    base-websocket-api: "wss://testnet.binance.vision/ws-api/v3" # Prod would be wss://ws-api.binance.com:443/ws-api/v3

trade:
    symbol: "PEPEFDUSD" # pepe coin obviously it's a pepe-trader for duck's sake
    base-asset: PEPE
    base-asset-scale: 0
    quote-asset: FDUSD
    quote-asset-scale: 8
    quote-asset-quantity-per-trade: 25.00
    gap-size-points: 4
    upper-bounds: 0.00000850
    lower-bounds: 0.00000650
    discord-webhook: <redacted>


logging.level:
    org: info
    at.pepe.trader: info
